cmdargs:
    severity: style_problem

env:
    neovim: true

policies:
    ProhibitSetNoCompatible:
        enabled: false
    ProhibitImplicitScopeVariable:
        enabled: false
    ProhibitEqualTildeOperator:
        enabled: false
